# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aeafc9ae82b56c1644eedec74d070f603116da6e6dcfa7c40f94679b72cd659d757fd6da1ff19d4c1429dc0cc35d7f509e0ff4ed64d0b1c774b4fb909e90641b

test:
  secret_key_base: 419b9dd6c1b7cfeb9c3db77ab178baf0331ca5963a30bb545d69ac759d036f816b21eaee484ab826ece4f46f3893f3caba7cbb657d05948214b59ec8f378dd95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
